// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNdlVOX5EaFXPZok7VT_WhqlIfnCJn4M',
    appId: '1:66746967075:web:0392ccbb26319cb3a13d96',
    messagingSenderId: '66746967075',
    projectId: 'emenza-8a1ed',
    authDomain: 'emenza-8a1ed.firebaseapp.com',
    storageBucket: 'emenza-8a1ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMV2dxnrYxRU03i4n8lO_snLHzcQVNltY',
    appId: '1:66746967075:android:4f26e68bc0f2f058a13d96',
    messagingSenderId: '66746967075',
    projectId: 'emenza-8a1ed',
    storageBucket: 'emenza-8a1ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNZ6YUKHu-rxKaUd4sZ7Ht0tDb8Qkke0',
    appId: '1:66746967075:ios:cac2a16c5c2498bda13d96',
    messagingSenderId: '66746967075',
    projectId: 'emenza-8a1ed',
    storageBucket: 'emenza-8a1ed.firebasestorage.app',
    iosBundleId: 'com.example.eMenza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNZ6YUKHu-rxKaUd4sZ7Ht0tDb8Qkke0',
    appId: '1:66746967075:ios:cac2a16c5c2498bda13d96',
    messagingSenderId: '66746967075',
    projectId: 'emenza-8a1ed',
    storageBucket: 'emenza-8a1ed.firebasestorage.app',
    iosBundleId: 'com.example.eMenza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtNdlVOX5EaFXPZok7VT_WhqlIfnCJn4M',
    appId: '1:66746967075:web:f6c0774a9b8be54ca13d96',
    messagingSenderId: '66746967075',
    projectId: 'emenza-8a1ed',
    authDomain: 'emenza-8a1ed.firebaseapp.com',
    storageBucket: 'emenza-8a1ed.firebasestorage.app',
  );
}
